CREATE TABLE `user_management`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST NAME` VARCHAR(225) NOT NULL,
  `LAST NAME` VARCHAR(225) NOT NULL,
  `EMAIL` VARCHAR(225) NOT NULL,
  `PHONE` VARCHAR(225) NOT NULL,
  `COMMENTS` MEDIUMTEXT NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`ID`));
